function analogChannels = importAnalog(workbookFile, sheetName, startRow, endRow)
%IMPORTFILE Import data from a spreadsheet
%  LIJ136EXTCHANNELS = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  LIJ136EXTCHANNELS = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  LIJ136EXTCHANNELS = IMPORTFILE(FILE, SHEET, STARTROW, ENDROW) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify STARTROW and ENDROW as a pair of scalars or vectors of
%  matching size for dis-contiguous row intervals.
%
%  Example:
%  LIJ136ExtChannels = importfile("/mnt/5638E68A38E66887/ECoGData/Tobii/Patients/NS136/LIJ136_ExtChannels.xlsx", "Sheet1", 3, 6);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Nov-2018 16:44:49

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 3;
    endRow = 6;
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + startRow(1) + ":B" + endRow(1);

% Specify column names and types
opts.VariableNames = ["Channel", "Label"];
opts.VariableTypes = ["double", "string"];
opts = setvaropts(opts, 2, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 2, "EmptyFieldRule", "auto");

% Import the data
analogChannels = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:length(startRow)
    opts.DataRange = "A" + startRow(idx) + ":B" + endRow(idx);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    analogChannels = [analogChannels; tb]; %#ok<AGROW>
end

end